### PR TITLE
Fix #46

### LINKED ISSUE #46: Word wrap is a bit broken
@Mitch528 
typing the following
```
I made the unofficial devRant client for Windows 10.
```
in subtext, the `10.` doesn't get wrapped

the font size has been changed (to a smaller font size)
see the latest commit https://github.com/devBanner/devBanner/commit/92ed56da9c196e28f2a3b64df6453b18aa1b9dce

### PR DESCRIPTION
**Pull request by Etnath**
fix issue #46.
The space character were not taken into account when calaculating text width in the AddWrap function

### CODE REVIEW

**Comment by Etnath** [comment]
Sorry, just read I should have done that on my fork instead of branching. I will do that next time.

**Comment by cozyplanes** [comment]
@Etnath nvm

**Comment by cozyplanes** [comment]
Looks lit!

**Comment by cozyplanes** [comment]
@kimmax time to update cuz you don't want me to use travis ^v^

**Pull request merged**
