### PR TITLE
[WIP] Add word wrapping

### PR DESCRIPTION
**Pull request by Mitch528**
Adds word wrapping to banner subtext.

It probably needs some additional tweaks in regards to positioning & scaling, but so far it seems to work pretty well.

### CODE REVIEW

**Comment by Mitch528** [comment]
I believe I have fixed the aforementioned issues now.

**Comment by Kimmax** [comment]
Perfect!

**Comment by cozyplanes** [comment]
Is this pushed to server?

**Comment by Kimmax** [comment]
not yet

**Pull request merged**
